/*
 * k8slbrp API
 *
 * k8slbrp API generated from k8slbrp.yang
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Service struct {
	// Service name related to the backend server of the pool is connected to
	Name string `json:"name,omitempty"`
	// Virtual IP (vip) of the service where clients connect to
	Vip string `json:"vip,omitempty"`
	// Port of the virtual server where clients connect to (this value is ignored in case of ICMP)
	Vport int32 `json:"vport,omitempty"`
	// Upper-layer protocol associated with a loadbalancing service instance. 'ALL' creates an entry for all the supported protocols
	Proto string `json:"proto,omitempty"`
	// Pool of backend servers that actually serve requests
	Backend []ServiceBackend `json:"backend,omitempty"`
}
