/*
 * k8slbrp API
 *
 * k8slbrp API generated from k8slbrp.yang
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SrcIpRewrite struct {
	// Range of IP addresses of the clients that must be replaced
	IpRange string `json:"ip-range,omitempty"`
	// Range of IP addresses of the that must be used to replace client addresses
	NewIpRange string `json:"new_ip_range,omitempty"`
}
