/*
 * k8sdispatcher API
 *
 * k8sdispatcher API generated from k8sdispatcher.yang
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NattingRule struct {
	// Source IP address
	InternalSrc string `json:"internal-src,omitempty"`
	// Destination IP address
	InternalDst string `json:"internal-dst,omitempty"`
	// Source L4 port number
	InternalSport int32 `json:"internal-sport,omitempty"`
	// Destination L4 port number
	InternalDport int32 `json:"internal-dport,omitempty"`
	// L4 protocol
	Proto string `json:"proto,omitempty"`
	// Translated IP address
	ExternalIp string `json:"external-ip,omitempty"`
	// Translated L4 port number
	ExternalPort int32 `json:"external-port,omitempty"`
}
