---
kind: ConfigMap
apiVersion: v1
metadata:
  name: polykube-cfg
  namespace: kube-system
data:
  apiServerIp: "REPLACE_WITH_API_SERVER_IP"
  apiServerPort: "REPLACE_WITH_API_SERVER_PORT"
  vxlanIfaceName: "vxlan0"
  polykubeVethPairNamePrefix: "polykube"
  vtepCidr: "10.18.0.0/16"
  clusterCidr: "192.178.0.0/16"
  nodePortRange: "30000-32767"
  cniConfFilePath: "/host/etc/cni/net.d/00-polykube.json"
  mtu: "1450"
  intLbrpName: "ilb0"
  routerName: "r0"
  extLbrpName: "elb0"
  k8sDispName: "k0"
  # The cubes log level can assume one of the following values:
  # "TRACE", "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL", "OFF"
  cubesLogLevel: "INFO"
  # The CNI log level can assume one of the following values:
  # "TRACE", "DEBUG", "INFO", "WARN", "WARNING", "FATAL", "PANIC", "OFF"
  cniLogLevel: "INFO"
  # if the following is set to true, the following toleration has to be
  # added to the daemonset tolerations:
  # - effect: NoSchedule
  #   key: node-role.kubernetes.io/master
  isCPNodesDeployAllowed: "true"