apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: polykube-ctrl-mgr-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: polykube-ctrl-mgr-role
subjects:
- kind: ServiceAccount
  name: polykube-ctrl-mgr-sa
  namespace: kube-system
