/*
 * k8sdispatcher API
 *
 * k8sdispatcher API generated from k8sdispatcher.yang
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SessionRule struct {
	// Session entry direction (e.g. INGRESS or EGRESS)
	Direction string `json:"direction,omitempty"`
	// Session entry source IP address
	SrcIp string `json:"src-ip,omitempty"`
	// Session entry destination IP address
	DstIp string `json:"dst-ip,omitempty"`
	// Session entry source L4 port number
	SrcPort int32 `json:"src-port,omitempty"`
	// Session entry destination L4 port number
	DstPort int32 `json:"dst-port,omitempty"`
	// Session entry L4 protocol
	Proto string `json:"proto,omitempty"`
	// Translated IP address
	NewIp string `json:"new-ip,omitempty"`
	// Translated L4 port number
	NewPort int32 `json:"new-port,omitempty"`
	// Operation applied on the original packet
	Operation string `json:"operation,omitempty"`
	// Rule originating the session entry
	OriginatingRule string `json:"originating-rule,omitempty"`
}
