/*
 * k8sdispatcher API
 *
 * k8sdispatcher API generated from k8sdispatcher.yang
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NodeportRule struct {
	// NodePort rule nodeport port number
	NodeportPort int32 `json:"nodeport-port,omitempty"`
	// NodePort rule L4 protocol
	Proto string `json:"proto,omitempty"`
	// The external traffic policy of the Kubernetes NodePort Service
	ExternalTrafficPolicy string `json:"external-traffic-policy,omitempty"`
	// An optional name for the NodePort rule
	RuleName string `json:"rule-name,omitempty"`
}
