/*
 * k8sdispatcher API
 *
 * k8sdispatcher API generated from k8sdispatcher.yang
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NodeportRule struct {
	// Source IP address
	Name string `json:"name,omitempty"`
	// Destination L4 port number
	Port int32 `json:"port,omitempty"`
	// L4 protocol
	Proto string `json:"proto,omitempty"`
	// Denotes if this Service desires to route external traffic to node-local or cluster-wide endpoint
	ServiceType string `json:"service-type,omitempty"`
}
