resources:
- bases/env.yaml
patchesJson6902:
- path: patches/basic.env.yaml
  target:
    group: scorecard.operatorframework.io
    version: v1alpha3
    kind: Configuration
    name: env
- path: patches/olm.env.yaml
  target:
    group: scorecard.operatorframework.io
    version: v1alpha3
    kind: Configuration
    name: env
#+kubebuilder:scaffold:patchesJson6902
