/*
 * router API
 *
 * router API generated from router.yang
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Router struct {
	// Name of the router service
	Name string `json:"name,omitempty"`
	// UUID of the Cube
	Uuid string `json:"uuid,omitempty"`
	// Type of the Cube (TC, XDP_SKB, XDP_DRV)
	Type_       string `json:"type,omitempty"`
	ServiceName string `json:"service-name,omitempty"`
	// Defines the logging level of a service instance, from none (OFF) to the most verbose (TRACE)
	Loglevel string `json:"loglevel,omitempty"`
	// Entry of the ports table
	Ports []Ports `json:"ports,omitempty"`
	// Defines if the service is visible in Linux
	Shadow bool `json:"shadow,omitempty"`
	// Defines if all traffic is sent to Linux
	Span bool `json:"span,omitempty"`
	// Entry associated with the routing table
	Route []Route `json:"route,omitempty"`
	// Entry associated with the ARP table
	ArpTable []ArpTable `json:"arp-table,omitempty"`
}
