/*
 * lbrp API
 *
 * lbrp API generated from lbrp.yang
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ServiceBackend struct {
	// name
	Name string `json:"name,omitempty"`
	// IP address of the backend server of the pool
	Ip string `json:"ip,omitempty"`
	// Port where the server listen to (this value is ignored in case of ICMP)
	Port int32 `json:"port,omitempty"`
	// Weight of the backend in the pool
	Weight int32 `json:"weight,omitempty"`
}
