/*
 * simplebridge API
 *
 * simplebridge API generated from simplebridge.yang
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type FdbFlushOutput struct {
	// Returns true if the Filtering database has been flushed. False otherwise
	Flushed bool `json:"flushed,omitempty"`
}
