/*
 * simplebridge API
 *
 * simplebridge API generated from simplebridge.yang
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type FdbEntry struct {
	// Address of the filtering database entry
	Address string `json:"address,omitempty"`
	// Output port name
	Port string `json:"port,omitempty"`
	// Age of the current filtering database entry
	Age int32 `json:"age,omitempty"`
}
