/*
 * router API
 *
 * router API generated from router.yang
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package router

type PortsSecondaryip struct {
	// Secondary IP address and prefix of the port
	Ip string `json:"ip,omitempty"`
}
